@startuml
left to right direction
skinparam packageStyle rect

actor "Operator" as Operator
actor "Transit Manager" as TransitManager

rectangle "Public Transit Fleet Management System" {
    Operator --> (Timestamp Tracking)
    Operator --> (Operator Bus Stop Logging)
    Operator --> (GPS Tracking)
    Operator --> (User Registration)
    

    (Timestamp Tracking) .> (Timestamp Alert) : <<include>>

    (Operator Bus Stop Logging) .> (Route Management) : <<include>>
    (Maintenance Request) <-- TransitManager

    (GPS Tracking) .> (Fuel/Energy Monitoring) : <<include>>
    (GPS Tracking) <. (Fuel/Energy Alerts) : <<exclude>>
    (User Registration) .> (Authentication) : <<include>>
    
    (Authentication) <-- TransitManager
    (Route Management) <--TransitManager
    (Predictive Maintenance) <-- TransitManager
    (Reporting & Analytics) <--TransitManager
    (GPS Tracking) <--TransitManager
    
}

@enduml

