USE TRANSIT;
CREATE OR REPLACE VIEW VEHICLE_TIMETABLES AS 
SELECT VEHICLES.VEHICLE_ID, STOPS.STOP_NAME, STOPS.IS_STATION, SCHEDULED_STOP_TIMES.ARRIVAL, SCHEDULED_STOP_TIMES.DEPARTURE 
FROM SCHEDULED_STOP_TIMES
INNER JOIN TRIP_SCHEDULES ON TRIP_SCHEDULES.ID = SCHEDULED_STOP_TIMES.TRIP_SCHEDULE_ID
INNER JOIN VEHICLES ON VEHICLES.CURRENT_ASSIGNED_TRIP = TRIP_SCHEDULES.ID
INNER JOIN ROUTES ON ROUTES.ID = TRIP_SCHEDULES.ROUTE_ID
INNER JOIN ROUTE_STOPS ON route_stops.ID = SCHEDULED_STOP_TIMES.SEQ_STOP_ID
    AND route_stops.ROUTE_ID = ROUTES.ID
INNER JOIN STOPS ON STOPS.ID = ROUTE_STOPS.STOP_ID;

-- select * from vehicles;
-- select * from trip_schedules;